/* tslint:disable */
/**
 * This file was automatically generated by strapi-sdk.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Test {
  title: string;
  content: string;
  global?: string;
  testenum?: "Value1" | "Value2";
  testjson?: unknown;
}
